apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app-test
  template:
    metadata:
      labels:
        app: python-app-test
    spec:
      containers:
      - name: app
        image: python-app:latest
        ports:
        - containerPort: 5000
