global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'generic-app'
    static_configs:
      - targets: ['generic-app:8080']  # App metrics endpoint
    metrics_path: /metrics

  - job_name: 'node-exporter'  # Infra metrics
    static_configs:
      - targets: ['node-exporter:9100']

rule_files:
  - 'alert.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

alertmanager_config:
  service: null
  receivers:
    - name: 'teams-team'
